"""leanmap — LEarn ANother MAPping.

Parametric landmark-conditioned neighbour embedding with a cohesive
multi-scale graph pyramid. After training, inference is a single network
forward pass.
"""

from __future__ import annotations

# Must be set before torch initializes the MPS backend so ops missing on Metal
# fall back to CPU (e.g. some cdist / deterministic kernels).
import os

os.environ.setdefault("PYTORCH_ENABLE_MPS_FALLBACK", "1")

from .conditioning import (
    RETENTION_CHANCE,
    ConditioningFactor,
    FactorStack,
    FactorViewMetric,
    Role,
    build_factor_stack,
    default_primary_factor,
    identity_view,
    metric_from_factors,
    scale_quotient_factorization,
    validate_factors,
)
from .classaxis import (
    CLASS_MARGIN,
    ORDER_CHANCE,
    AxisLoadings,
    ClassAxis,
    ClassAxisReadout,
    ClassOrderSampler,
    ClassRegionConformal,
    axis_loadings,
    class_axis_report,
    class_direction_loss,
    class_order_loss,
    direction_tilt,
    free_direction,
    grouped_class_axis,
    ordinal_class_axis,
    validate_class_axes,
)
from .path import (
    PATH_C,
    PATH_C_HI,
    PATH_MARGIN,
    PATH_ORD_CHANCE,
    PathConstraint,
    PathTripletSampler,
    build_path_triplets,
    encode_groups,
    parse_index,
    path_constraint_loss,
    remap_triplets,
    subset_by_group,
)
from .config import (
    BuildConfig,
    PLANEConfig,
    PolicyConfig,
    StoreConfig,
    TrainConfig,
    compose_plane_config,
)
from .conformal import (
    MONDRIAN_GROUPS,
    NONCONFORMITY_SCORES,
    ConformalCalibrator,
    CoverEntropyLDA,
    LandmarkSupport,
    MondrianCalibrator,
    bh_reject,
    conformal_threshold,
    cover_entropy_features,
    geometry_consistency_score,
    list_nonconformity_scores,
    make_mondrian_groups,
)
from .distance import (
    CallableDistance,
    CosineDistance,
    DistanceFn,
    EuclideanDistance,
    ManhattanDistance,
    SquaredEuclideanDistance,
    chunked_cdist,
    is_differentiable,
)
from .emd import (
    geodesic_from_matrix,
    geodesic_submatrix,
    grid_cost_matrix,
    image_emd,
    image_masses,
    pairwise_emd,
    reference_knn_overlap,
    reference_retrieval_overlap,
    reference_shepard,
    reference_trust_continuity,
)
from .evaluate import (
    benchmark_inference,
    geodesic_fidelity,
    knn_recall_out_of_sample,
    density_correspondence,
    knn_local_density,
    neighborhood_rank_agreement,
    persistence_summary,
    procrustes_disagreement,
    shepard_pairs_ambient,
    shepard_pairs_geodesic,
    shepard_stats,
    trustworthiness_continuity,
    uniformity_of_pvalues,
)
from .graph import (
    Graph,
    GraphStats,
    Representatives,
    build_graph,
    build_graph_pyramid,
    load_graph_pyramid,
    save_graph_pyramid,
    smooth_knn,
    union_assign_topc,
    validate_precomputed_knn,
)
from .landmarks import (
    AnchorAffinity,
    LandmarkAffinity,
    assign_buckets,
    fps_init,
    init_anchors,
    landmark_geodesic_matrix,
    poisson_disk_indices_geodesic,
    quantile_init,
)
from .metrics import CompositeMetric, MetricSpec, get_metric, wrap_metric
from .model import ConcatEncoder, FiLMEncoder, PLANE, fit_pca_weight
from .probes import (
    CONTROL_PROBES,
    PROBE_PATTERNS,
    control_probes,
    probe_pattern_names,
    render_pattern,
    structured_probes,
)
from .negative_space import (
    ALL_FEATURES,
    DM_ONLY_FEATURES,
    DistanceQuantileHead,
    NegativeSpaceModel,
    PerturbationConfig,
    build_labeled_set,
    calibrate_novelty,
    distance_to_support,
    extract_features,
    fit_negative_space,
    NoveltyDetector,
    sample_perturbations,
)
from .train import PLANEResult, fit, load_plane

__version__ = "0.3.0"

__all__ = [
    "PLANEConfig",
    "BuildConfig",
    "StoreConfig",
    "TrainConfig",
    "PolicyConfig",
    "compose_plane_config",
    "PLANE",
    "PLANEResult",
    "fit",
    "load_plane",
    "Role",
    "AxisLoadings",
    "ClassAxis",
    "ClassAxisReadout",
    "ClassOrderSampler",
    "ClassRegionConformal",
    "ordinal_class_axis",
    "grouped_class_axis",
    "axis_loadings",
    "class_axis_report",
    "class_order_loss",
    "class_direction_loss",
    "free_direction",
    "direction_tilt",
    "validate_class_axes",
    "CLASS_MARGIN",
    "ORDER_CHANCE",
    "PathConstraint",
    "PathTripletSampler",
    "path_constraint_loss",
    "build_path_triplets",
    "encode_groups",
    "parse_index",
    "remap_triplets",
    "subset_by_group",
    "PATH_C",
    "PATH_C_HI",
    "PATH_MARGIN",
    "PATH_ORD_CHANCE",
    "ConditioningFactor",
    "FactorStack",
    "FactorViewMetric",
    "RETENTION_CHANCE",
    "identity_view",
    "default_primary_factor",
    "build_factor_stack",
    "scale_quotient_factorization",
    "metric_from_factors",
    "validate_factors",
    "DistanceFn",
    "EuclideanDistance",
    "SquaredEuclideanDistance",
    "CosineDistance",
    "ManhattanDistance",
    "CallableDistance",
    "chunked_cdist",
    "is_differentiable",
    "MetricSpec",
    "CompositeMetric",
    "get_metric",
    "wrap_metric",
    "fps_init",
    "poisson_disk_indices_geodesic",
    "landmark_geodesic_matrix",
    "quantile_init",
    "init_anchors",
    "assign_buckets",
    "AnchorAffinity",
    "LandmarkAffinity",
    "Graph",
    "GraphStats",
    "Representatives",
    "build_graph",
    "build_graph_pyramid",
    "save_graph_pyramid",
    "load_graph_pyramid",
    "validate_precomputed_knn",
    "smooth_knn",
    "union_assign_topc",
    "FiLMEncoder",
    "ConcatEncoder",
    "fit_pca_weight",
    "ConformalCalibrator",
    "LandmarkSupport",
    "MondrianCalibrator",
    "CoverEntropyLDA",
    "MONDRIAN_GROUPS",
    "NONCONFORMITY_SCORES",
    "geometry_consistency_score",
    "cover_entropy_features",
    "conformal_threshold",
    "list_nonconformity_scores",
    "make_mondrian_groups",
    "bh_reject",
    "fit_negative_space",
    "calibrate_novelty",
    "NoveltyDetector",
    "NegativeSpaceModel",
    "DistanceQuantileHead",
    "PerturbationConfig",
    "build_labeled_set",
    "sample_perturbations",
    "extract_features",
    "distance_to_support",
    "ALL_FEATURES",
    "DM_ONLY_FEATURES",
    "trustworthiness_continuity",
    "knn_recall_out_of_sample",
    "benchmark_inference",
    "uniformity_of_pvalues",
    "geodesic_fidelity",
    "shepard_stats",
    "shepard_pairs_ambient",
    "shepard_pairs_geodesic",
    "knn_local_density",
    "density_correspondence",
    "procrustes_disagreement",
    "neighborhood_rank_agreement",
    "persistence_summary",
    "grid_cost_matrix",
    "image_masses",
    "image_emd",
    "pairwise_emd",
    "geodesic_from_matrix",
    "geodesic_submatrix",
    "reference_shepard",
    "reference_trust_continuity",
    "reference_knn_overlap",
    "reference_retrieval_overlap",
    "PROBE_PATTERNS",
    "CONTROL_PROBES",
    "probe_pattern_names",
    "render_pattern",
    "structured_probes",
    "control_probes",
    "__version__",
]
